version: '3.7'

services:
  web:
    build: 
      dockerfile: ./apps/web/Dockerfile
      context: .
      cache_from:
      - matnbaz:base
    env_file:
      - .env
    ports: 
      - ${WEB_PORT}:${WEB_PORT}
    command: yarn start web
    depends_on:
      - server

  server:
    build: 
      dockerfile: ./apps/server/Dockerfile
      context: .
      cache_from:
      - matnbaz:base
    env_file:
      - .env
    environment:
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${DB_HOST}:${DB_PORT}/${POSTGRES_DB}?schema=${DB_SCHEMA}&connect_timeout=300
    ports:
      - ${API_PORT}:${API_PORT}
      # - 9229:9229 # NodeJS debugging port
    command: yarn start server
    networks:
      - webnet
    depends_on:
      - redis
      - postgres
      
  redis:
    image: redis:5
    networks:
      - webnet

  postgres:
    image: postgres:12
    restart: always
    networks:
      - webnet
    environment:
      PG_DATA: /var/lib/postgresql/data
    env_file:
    - .env
    volumes:
      - pgdata:/var/lib/postgresql/data
networks:
  webnet:
volumes:
  pgdata: